version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - SERVER_PORT=8080
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "project=whoami"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8081:80"   # mappe le port 80 du container sur le port 8081 du VPS
    labels:
      - "project=whoami"
    healthcheck:      # ajoute un healthcheck simple
      test: ["CMD", "curl", "-f", "http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s