version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - SERVER_PORT=8080
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "project=whoami"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    expose:
      - "80"
    labels:
      - "project=whoami"