package com.purplerockstudios.whoami.personality;

import org.springframework.context.annotation.Configuration;

import java.util.HashMap;
import java.util.Map;

@Configuration
public class PersonnalityMap {
	private HashMap<String, Boolean> personalities = new HashMap<>();

	PersonnalityMap() {
		personalities.put("Albert Einstein", false);
		personalities.put("Marie Curie", false);
		personalities.put("Isaac Newton", false);
		personalities.put("Nikola Tesla", false);
		personalities.put("Stephen Hawking", false);
		personalities.put("Rosalind Franklin", false);
		personalities.put("Richard Feynman", false);
		personalities.put("Charles Darwin", false);
		personalities.put("Carl Sagan", false);
		personalities.put("Jane Goodall", false);
		personalities.put("William Shakespeare", false);
		personalities.put("Jane Austen", false);
		personalities.put("Mark Twain", false);
		personalities.put("J.K. Rowling", false);
		personalities.put("Gabriel García Márquez", false);
		personalities.put("Leo Tolstoy", false);
		personalities.put("Ernest Hemingway", false);
		personalities.put("George Orwell", false);
		personalities.put("Virginia Woolf", false);
		personalities.put("Haruki Murakami", false);
		personalities.put("Ludwig van Beethoven", false);
		personalities.put("Wolfgang Amadeus Mozart", false);
		personalities.put("Bob Dylan", false);
		personalities.put("Freddie Mercury", false);
		personalities.put("Beyoncé", false);
		personalities.put("John Lennon", false);
		personalities.put("Elvis Presley", false);
		personalities.put("Johann Sebastian Bach", false);
		personalities.put("Madonna", false);
		personalities.put("Michael Jackson", false);
		personalities.put("Steven Spielberg", false);
		personalities.put("Alfred Hitchcock", false);
		personalities.put("Meryl Streep", false);
		personalities.put("Robert De Niro", false);
		personalities.put("Audrey Hepburn", false);
		personalities.put("Leonardo DiCaprio", false);
		personalities.put("Martin Scorsese", false);
		personalities.put("Charlie Chaplin", false);
		personalities.put("Quentin Tarantino", false);
		personalities.put("Natalie Portman", false);
		personalities.put("Michael Jordan", false);
		personalities.put("Serena Williams", false);
		personalities.put("Lionel Messi", false);
		personalities.put("Cristiano Ronaldo", false);
		personalities.put("Usain Bolt", false);
		personalities.put("Muhammad Ali", false);
		personalities.put("Roger Federer", false);
		personalities.put("Simone Biles", false);
		personalities.put("Pelé", false);
		personalities.put("LeBron James", false);
		personalities.put("Mahatma Gandhi", false);
		personalities.put("Nelson Mandela", false);
		personalities.put("Winston Churchill", false);
		personalities.put("Margaret Thatcher", false);
		personalities.put("Barack Obama", false);
		personalities.put("Angela Merkel", false);
		personalities.put("Martin Luther King Jr.", false);
		personalities.put("Franklin D. Roosevelt", false);
		personalities.put("John F. Kennedy", false);
		personalities.put("Indira Gandhi", false);
		personalities.put("Technologie", false);
		personalities.put("Steve Jobs", false);
		personalities.put("Bill Gates", false);
		personalities.put("Mark Zuckerberg", false);
		personalities.put("Jeff Bezos", false);
		personalities.put("Larry Page", false);
		personalities.put("Sergey Brin", false);
		personalities.put("Tim Berners-Lee", false);
		personalities.put("Marissa Mayer", false);
		personalities.put("Sheryl Sandberg", false);
		personalities.put("Pablo Picasso", false);
		personalities.put("Vincent van Gogh", false);
		personalities.put("Leonardo da Vinci", false);
		personalities.put("Andy Warhol", false);
		personalities.put("Salvador Dalí", false);
		personalities.put("Michelangelo", false);
		personalities.put("Claude Monet", false);
		personalities.put("Rembrandt", false);
		personalities.put("Socrate", false);
		personalities.put("Platon", false);
		personalities.put("Aristote", false);
		personalities.put("Immanuel Kant", false);
		personalities.put("Friedrich Nietzsche", false);
		personalities.put("Jean-Paul Sartre", false);
		personalities.put("Simone de Beauvoir", false);
		personalities.put("Confucius", false);
		personalities.put("John Locke", false);
		personalities.put("Thomas Hobbes", false);
		personalities.put("Coco Chanel", false);
		personalities.put("Giorgio Armani", false);
		personalities.put("Yves Saint Laurent", false);
		personalities.put("Karl Lagerfeld", false);
		personalities.put("Donatella Versace", false);
		personalities.put("Ralph Lauren", false);
		personalities.put("Vivienne Westwood", false);
		personalities.put("Christian Dior", false);
		personalities.put("Alexander McQueen", false);
		personalities.put("Jean Paul Gaultier", false);
		personalities.put("Niels Bohr", false);
		personalities.put("Ada Lovelace", false);
		personalities.put("Galileo Galilei", false);
		personalities.put("James Clerk Maxwell", false);
		personalities.put("Edwin Hubble", false);
		personalities.put("Barbara McClintock", false);
		personalities.put("Richard Dawkins", false);
		personalities.put("Rachel Carson", false);
		personalities.put("Gregor Mendel", false);
		personalities.put("Alan Turing", false);
		personalities.put("Fyodor Dostoevsky", false);
		personalities.put("Emily Dickinson", false);
		personalities.put("Franz Kafka", false);
		personalities.put("Harper Lee", false);
		personalities.put("Miguel de Cervantes", false);
		personalities.put("J.R.R. Tolkien", false);
		personalities.put("Charles Dickens", false);
		personalities.put("Sylvia Plath", false);
		personalities.put("James Joyce", false);
		personalities.put("Toni Morrison", false);
		personalities.put("Johann Strauss II", false);
		personalities.put("Igor Stravinsky", false);
		personalities.put("Prince", false);
		personalities.put("David Bowie", false);
		personalities.put("Rihanna", false);
		personalities.put("Paul McCartney", false);
		personalities.put("Whitney Houston", false);
		personalities.put("Ella Fitzgerald", false);
		personalities.put("Frank Sinatra", false);
		personalities.put("Francis Ford Coppola", false);
		personalities.put("Stanley Kubrick", false);
		personalities.put("Al Pacino", false);
		personalities.put("Ingrid Bergman", false);
		personalities.put("Tom Hanks", false);
		personalities.put("Ridley Scott", false);
		personalities.put("Buster Keaton", false);
		personalities.put("Sofia Coppola", false);
		personalities.put("Jennifer Lawrence", false);
		personalities.put("Tiger Woods", false);
		personalities.put("Nadia Comăneci", false);
		personalities.put("Diego Maradona", false);
		personalities.put("Mia Hamm", false);
		personalities.put("Michael Phelps", false);
		personalities.put("Jackie Robinson", false);
		personalities.put("Jesse Owens", false);
		personalities.put("Martina Navratilova", false);
		personalities.put("Ayrton Senna", false);
		personalities.put("Magic Johnson", false);
		personalities.put("Abraham Lincoln", false);
		personalities.put("Theodore Roosevelt", false);
		personalities.put("Golda Meir", false);
		personalities.put("Angela Davis", false);
		personalities.put("Che Guevara", false);
		personalities.put("Aung San Suu Kyi", false);
		personalities.put("Malala Yousafzai", false);
		personalities.put("Linus Torvalds", false);
		personalities.put("Grace Hopper", false);
		personalities.put("Hedy Lamarr", false);
		personalities.put("Satya Nadella", false);
		personalities.put("Jack Ma", false);
		personalities.put("Susan Wojcicki", false);
		personalities.put("Sundar Pichai", false);
		personalities.put("Meg Whitman", false);
		personalities.put("Jack Dorsey", false);
		personalities.put("Elon Musk", false);
		personalities.put("Arts visuels", false);
		personalities.put("Jackson Pollock", false);
		personalities.put("Henri Matisse", false);
		personalities.put("Gustav Klimt", false);
		personalities.put("Edvard Munch", false);
		personalities.put("Paul Gauguin", false);
		personalities.put("Georgia O'Keeffe", false);
		personalities.put("Keith Haring", false);
		personalities.put("Ansel Adams", false);
		personalities.put("Frida Kahlo", false);
		personalities.put("Diego Rivera", false);
		personalities.put("René Descartes", false);
		personalities.put("David Hume", false);
		personalities.put("Søren Kierkegaard", false);
		personalities.put("Bertrand Russell", false);
		personalities.put("Michel Foucault", false);
		personalities.put("Ludwig Wittgenstein", false);
		personalities.put("Hannah Arendt", false);
		personalities.put("Baruch Spinoza", false);
		personalities.put("John Stuart Mill", false);
		personalities.put("Epicurus", false);
		personalities.put("Gianni Versace", false);
		personalities.put("Miuccia Prada", false);
		personalities.put("Calvin Klein", false);
		personalities.put("Tom Ford", false);
		personalities.put("Carolina Herrera", false);
		personalities.put("Diane von Fürstenberg", false);
		personalities.put("Michael Kors", false);
		personalities.put("Pierre Cardin", false);
		personalities.put("Thierry Mugler", false);
		personalities.put("Oscar de la Renta", false);
		personalities.put("Adele", false);
		personalities.put("Ed Sheeran", false);
		personalities.put("Billie Eilish", false);
		personalities.put("Kendrick Lamar", false);
		personalities.put("Lady Gaga", false);
		personalities.put("Justin Bieber", false);
		personalities.put("Alicia Keys", false);
		personalities.put("Bruno Mars", false);
		personalities.put("Shakira", false);
		personalities.put("Drake", false);
		personalities.put("Ariana Grande", false);
		personalities.put("Sam Smith", false);
		personalities.put("Taylor Swift", false);
		personalities.put("The Weeknd", false);
		personalities.put("Demi Lovato", false);
		personalities.put("Shawn Mendes", false);
		personalities.put("Katy Perry", false);
		personalities.put("Post Malone", false);
		personalities.put("Dua Lipa", false);
		personalities.put("Camila Cabello", false);
		personalities.put("Emmanuel Macron", false);
		personalities.put("Xi Jinping", false);
		personalities.put("Justin Trudeau", false);
		personalities.put("Boris Johnson", false);
		personalities.put("Narendra Modi", false);
		personalities.put("Jair Bolsonaro", false);
		personalities.put("Scott Morrison", false);
		personalities.put("Cyril Ramaphosa", false);
		personalities.put("Jacinda Ardern", false);
		personalities.put("Andrés Manuel López Obrador", false);
		personalities.put("Yoshihide Suga", false);
		personalities.put("Recep Tayyip Erdoğan", false);
		personalities.put("Pedro Sánchez", false);
		personalities.put("Giuseppe Conte", false);
		personalities.put("Hassan Rouhani", false);
		personalities.put("Alberto Fernández", false);
		personalities.put("Abdel Fattah el-Sisi", false);
		personalities.put("Alexander Lukashenko", false);
		personalities.put("Tom Cruise", false);
		personalities.put("Brad Pitt", false);
		personalities.put("Scarlett Johansson", false);
		personalities.put("Denzel Washington", false);
		personalities.put("Julia Roberts", false);
		personalities.put("Chris Hemsworth", false);
		personalities.put("Charlize Theron", false);
		personalities.put("Ryan Reynolds", false);
		personalities.put("Sandra Bullock", false);
		personalities.put("Joaquin Phoenix", false);
		personalities.put("Hugh Jackman", false);
		personalities.put("Jennifer Aniston", false);
		personalities.put("Will Smith", false);
		personalities.put("Keanu Reeves", false);
		personalities.put("Margot Robbie", false);
		personalities.put("Dwayne Johnson", false);
		personalities.put("Emma Stone", false);
		personalities.put("Chris Evans", false);
		personalities.put("Gal Gadot", false);
		personalities.put("Harry Potter", false);
		personalities.put("Frodo Baggins", false);
		personalities.put("Wonder Woman", false);
		personalities.put("Spider-Man", false);
		personalities.put("Iron Man", false);
		personalities.put("Elsa ", false);
		personalities.put("Yoda", false);
		personalities.put("Darth Vader", false);
		personalities.put("Goku ", false);
		personalities.put("Sailor Moon", false);
		personalities.put("Wolverine", false);
		personalities.put("Captain America", false);
		personalities.put("Thor", false);
		personalities.put("Simba ", false);
		personalities.put("Optimus Prime", false);
		personalities.put("Sonic the Hedgehog", false);
		personalities.put("Lara Croft", false);
		personalities.put("Sherlock Holmes", false);
		personalities.put("Frank Ocean", false);
		personalities.put("Miley Cyrus", false);
		personalities.put("John Legend", false);
		personalities.put("Cardi B", false);
		personalities.put("Sia", false);
		personalities.put("Usher", false);
		personalities.put("Chris Brown", false);
		personalities.put("Ellie Goulding", false);
		personalities.put("Kacey Musgraves", false);
		personalities.put("Megan Thee Stallion", false);
		personalities.put("Blake Shelton", false);
		personalities.put("Gwen Stefani", false);
		personalities.put("Lizzo", false);
		personalities.put("Enrique Iglesias", false);
		personalities.put("Jason Derulo", false);
		personalities.put("Selena Gomez", false);
		personalities.put("Halsey", false);
		personalities.put("Zayn Malik", false);
		personalities.put("Charlie Puth", false);
		personalities.put("Bebe Rexha", false);
		personalities.put("Joe Biden", false);
		personalities.put("Vladimir Putin", false);
		personalities.put("Volodymyr Zelenskyy", false);
		personalities.put("Rodrigo Duterte", false);
		personalities.put("Kim Jong-un", false);
		personalities.put("Benjamin Netanyahu", false);
		personalities.put("Aleksandar Vučić", false);
		personalities.put("Viktor Orbán", false);
		personalities.put("Imran Khan", false);
		personalities.put("Andrzej Duda", false);
		personalities.put("Mateusz Morawiecki", false);
		personalities.put("Sauli Niinistö", false);
		personalities.put("Sebastián Piñera", false);
		personalities.put("Nicolás Maduro", false);
		personalities.put("Mohammed bin Salman", false);
		personalities.put("Sheikh Hasina", false);
		personalities.put("Ebrahim Raisi", false);
		personalities.put("Mette Frederiksen", false);
		personalities.put("Moon Jae-in", false);
		personalities.put("Christian Bale", false);
		personalities.put("Amy Adams", false);
		personalities.put("Matt Damon", false);
		personalities.put("Cate Blanchett", false);
		personalities.put("Jake Gyllenhaal", false);
		personalities.put("Anne Hathaway", false);
		personalities.put("Mark Ruffalo", false);
		personalities.put("Rachel McAdams", false);
		personalities.put("Idris Elba", false);
		personalities.put("Reese Witherspoon", false);
		personalities.put("Ben Affleck", false);
		personalities.put("Emily Blunt", false);
		personalities.put("Ryan Gosling", false);
		personalities.put("Viola Davis", false);
		personalities.put("Tom Hardy", false);
		personalities.put("Mila Kunis", false);
		personalities.put("Ewan McGregor", false);
		personalities.put("Kate Winslet", false);
		personalities.put("Mahershala Ali", false);
		personalities.put("Naomi Watts", false);
		personalities.put("Princess Leia", false);
		personalities.put("Hermione Granger", false);
		personalities.put("Tony Stark/Iron Man", false);
		personalities.put("Batman", false);
		personalities.put("Black Widow", false);
		personalities.put("James Bond", false);
		personalities.put("Katniss Everdeen", false);
		personalities.put("Indiana Jones", false);
		personalities.put("Jack Sparrow", false);
		personalities.put("Buzz Lightyear", false);
		personalities.put("Woody", false);
		personalities.put("Moana", false);
		personalities.put("Shrek", false);
		personalities.put("Mickey Mouse", false);
		personalities.put("Minnie Mouse", false);
		personalities.put("Gandalf", false);
	}

	public void setAllPersonnalitiesToFalse() {
		for (Map.Entry<String, Boolean> entry : this.personalities.entrySet()) {
			entry.setValue(false);
		}
	}

	public Map<String, Boolean> getPersonalities() {
		return personalities;
	}
}
